<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="43" started-at="2017-12-15T17:30:42Z" finished-at="2017-12-15T17:30:42Z">
    <groups>
      <group name="Debug">
        <method signature="TgDoubleTest.tgTest(java.lang.Double, java.lang.Double)[pri:0, instance:tests.testng.TgDoubleTest@707f7052]" name="tgTest" class="tests.testng.TgDoubleTest"/>
      </group> <!-- Debug -->
    </groups>
    <test name="Command line test" duration-ms="43" started-at="2017-12-15T17:30:42Z" finished-at="2017-12-15T17:30:42Z">
      <class name="tests.testng.TgDoubleTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:tests.testng.TgDoubleTest@707f7052]" name="beforeTest" is-config="true" duration-ms="6" started-at="2017-12-15T20:30:42Z" finished-at="2017-12-15T20:30:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="tgTest(java.lang.Double, java.lang.Double)[pri:0, instance:tests.testng.TgDoubleTest@707f7052]" name="tgTest" duration-ms="7" started-at="2017-12-15T20:30:42Z" data-provider="DataProviderTgDoubleTest" finished-at="2017-12-15T20:30:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-10.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Invalid tg() result expected [-10.0] but found [-0.96]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Invalid tg() result expected [-10.0] but found [-0.96]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at tests.testng.TgDoubleTest.tgTest(TgDoubleTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at runner.Main.main(Main.java:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tgTest -->
      </class> <!-- tests.testng.TgDoubleTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
