<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Pablo" name="tests.testng.DivDoubleTest" tests="1" failures="0" timestamp="15 дек 2017 05:40:08 GMT" time="0.000" errors="1">
  <testcase name="sumTest" time="0.000" classname="tests.testng.DivDoubleTest">
    <error type="org.testng.TestNGException" message="
Method public void tests.testng.DivDoubleTest.sumTest(double,double,double) requires a @DataProvider named : DataProviderForSumTest">
      <![CDATA[org.testng.TestNGException: 
Method public void tests.testng.DivDoubleTest.sumTest(double,double,double) requires a @DataProvider named : DataProviderForSumTest
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at runner.Main.main(Main.java:35)
]]>
    </error>
  </testcase> <!-- sumTest -->
</testsuite> <!-- tests.testng.DivDoubleTest -->
